# Generated by Django 5.2.17 on 2026-09-22 01:21

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('village', models.CharField(blank=True, max_length=100, verbose_name='Village / town')),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='artisans/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('nav_label', models.CharField(blank=True, help_text="Shorter name for the menu bar, e.g. 'Gifts' for 'Gifts & Corporate'.", max_length=40)),
                ('icon_key', models.CharField(choices=[('painting', 'Painting'), ('lotus', 'Lotus / motif'), ('home', 'Home decor'), ('lamp', 'Lamp'), ('pot', 'Handicraft pot'), ('scarf', 'Textile / scarf'), ('gift', 'Gift box'), ('brush', 'Custom art brush'), ('leaf', 'Leaf (default)')], default='leaf', help_text='Icon shown in the category circle on the home page.', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Shown in the round category tiles on the home page.', upload_to='categories/')),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers come first.')),
                ('show_in_nav', models.BooleanField(default=True, verbose_name='Show in menu bar')),
                ('show_on_home', models.BooleanField(default=True, verbose_name='Show on home page')),
                ('parent', models.ForeignKey(blank=True, help_text='Leave empty for a top-level category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('paid', 'Confirmed'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled'), ('review', 'Needs review')], db_index=True, default='pending', max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address_line1', models.CharField(max_length=200, verbose_name='Address')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='Address line 2')),
                ('city', models.CharField(max_length=100, verbose_name='City / town')),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(max_length=20, verbose_name='PIN code')),
                ('country', models.CharField(default='India', max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_provider', models.CharField(blank=True, max_length=20)),
                ('payment_reference', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Gateway order id')),
                ('payment_id', models.CharField(blank=True, max_length=255, verbose_name='Gateway payment id')),
                ('courier', models.CharField(blank=True, max_length=80)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('internal_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('details', models.CharField(blank=True, help_text='Short line under the name, e.g. size and material.', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Selling price (₹)')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text="Optional. If higher than the selling price, it is shown struck through with a '% off' label.", max_digits=10, null=True, verbose_name='MRP (₹)')),
                ('stock', models.PositiveIntegerField(default=1, help_text='Set to 1 for one-of-a-kind pieces. 0 shows the item as sold.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide the product from the shop entirely.')),
                ('is_featured', models.BooleanField(default=False, help_text="Show on the home page under 'Featured Products'.")),
                ('image', models.ImageField(blank=True, help_text='Cover photo.', upload_to='products/')),
                ('dimensions', models.CharField(blank=True, help_text='e.g. 24 x 36 in', max_length=100)),
                ('materials', models.CharField(blank=True, help_text='e.g. Handmade paper, natural pigments', max_length=140)),
                ('dispatch_days', models.PositiveSmallIntegerField(default=3, help_text='Working days needed to pack and dispatch.')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artisan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.artisan')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='shop.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=140)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='shop.product')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField(blank=True)),
                ('verified_purchase', models.BooleanField(default=False, editable=False)),
                ('is_approved', models.BooleanField(default=True, help_text='Untick to hide a review without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('product', 'user'), name='one_review_per_user_per_product')],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='one_wishlist_row_per_product')],
            },
        ),
    ]
