# Generated by Django 5.2.17 on 2026-09-23 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_shipped_by_seller',
            field=models.BooleanField(default=False, help_text="The seller's own record that they've packed/sent this item."),
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('bio', models.TextField(blank=True, help_text='Shown on your public seller page.')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, upload_to='sellers/')),
                ('is_approved', models.BooleanField(default=False, help_text='Products from this seller are only public once approved.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Snapshot of who was selling this item at order time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.sellerprofile'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, help_text="Empty means this is an official Bhoomija Designs listing rather than a marketplace seller's.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.sellerprofile'),
        ),
    ]
