# Generated by Django 5.2.17 on 2026-09-22 01:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('hero', 'Home page slider'), ('promo_left', 'Promo panel (left, green)'), ('promo_right', 'Promo panel (right, terracotta)')], default='hero', max_length=12)),
                ('eyebrow', models.CharField(blank=True, help_text='Small line above the title (slider only).', max_length=80)),
                ('title', models.CharField(help_text='Use a new line to break the title in two.', max_length=120)),
                ('highlight', models.CharField(blank=True, help_text='Coloured words after the title (slider only).', max_length=80)),
                ('text', models.TextField(blank=True)),
                ('button_label', models.CharField(blank=True, max_length=40)),
                ('link', models.CharField(blank=True, help_text='e.g. /shop/ or /category/home-decor/', max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='banners/')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['placement', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=140)),
                ('message', models.TextField()),
                ('is_handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomArtRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('quoted', 'Quote sent'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('closed', 'Closed')], db_index=True, default='new', max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(verbose_name='What would you like us to create?')),
                ('size', models.CharField(blank=True, max_length=60, verbose_name='Preferred size')),
                ('budget', models.CharField(choices=[('under-5000', 'Under ₹5,000'), ('5000-15000', '₹5,000 - ₹15,000'), ('15000-50000', '₹15,000 - ₹50,000'), ('over-50000', 'Over ₹50,000'), ('not-sure', 'Not sure yet')], default='not-sure', max_length=20)),
                ('reference_image', models.ImageField(blank=True, upload_to='custom_requests/', verbose_name='Reference image')),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField(help_text='HTML. Use <h2>, <p>, <ul> etc.')),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.CharField(blank=True, max_length=240)),
                ('body', models.TextField(help_text='HTML. Use <h2>, <p>, <ul> etc.')),
                ('cover', models.ImageField(blank=True, upload_to='blog/')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
